### ISSUE TITLE
Encountered an error when attempting to modify the levels

### ISSUE THREAD

**Issue by BabakAmini** [erezinman/loguru-config#1]
Currently, I'm using a YAML config file similar to the following:

```yaml
handlers:
  - sink: ext://sys.stderr
    format: '[{time}] {message}'
  - sink: file.log
    enqueue: true
    serialize: true

levels:
  - name: NEW
    'no': 13
    icon: ¤
    color: ""
```

Once the code has been executed, it will be necessary at a certain stage to invoke a function similar to the one below in order to dynamically adjust all handler levels to a new value:

```py
    def config_loguru(level):
        cfg = LoguruConfig().load('loguru.yml', configure=False)
        
        for h in cfg.handlers:
            h['level'] = level

        cfg.parse().configure()
```

but I get an exception message like this:

```py
File "/home/babak/env_311/lib/python3.11/site-packages/loguru_config/loguru_config.py", line 106, in configure
    return logger.configure(
           ^^^^^^^^^^^^^^^^^
    File "/home/babak/env_311/lib/python3.11/site-packages/loguru/_logger.py", line 1736, in configure
      self.level(**params)
    File "/home/babak/env_311/lib/python3.11/site-packages/loguru/_logger.py", line 1588, in level
      raise TypeError("Level '%s' already exists, you can't update its severity no" % name)
TypeError: Level 'NEW' already exists, you can't update its severity no
```

From my understanding, calling `loguru.configure()` resets all settings in the logger hierarchy. However, it appears that previously added levels are not reset in this case. Adding `logger.remove()` before reconfiguring also doesn't help.

What is wrong with this approach, and what can I do to change the level of all handlers in the logger?

**Comment by erezinman** [comment]
This is a bug(?) in `loguru`.  You can write it there. There is, however, a workaround. You can call the (internal and undocumented) `logger._core.__init__()` configuration. This resets the logger (or most of it), including the defined levels. That is:

```python

    def config_loguru(level):
        cfg = LoguruConfig().load('loguru.yml', configure=False)
        
        for h in cfg.handlers:
            h['level'] = level

        # --------------------------
        logger._core.__init__()
        # --------------------------

        cfg.parse().configure()
```

Tell me if that solved your issue.

**Comment by Delgan** [comment]
Hi there. :)

Looking at the problem reported by @BabakAmini, I wouldn't call it a bug. Loguru does not allow re-configuring the severity of already existing levels.

If I understand correctly, the problem is that `config_loguru()` is called multiple times, which causes the `"NEW"` level to be added twice while this is forbidden.

I think you should drop the `levels` attribute from the config `dict` if you call `config_loguru()` a second time.

**Comment by BabakAmini** [comment]
@erezinman, your solution effectively resolved my problem. However, I'm concerned that accessing the private members of the class would violate Python coding standards. @Delgan also mentioned this [here](https://github.com/Delgan/loguru/issues/138#issuecomment-793090622).

> If I understand correctly, the problem is that config_loguru() is called multiple times, which causes the "NEW" level to be added twice while this is forbidden.

I'm not calling `config_loguru()` multiple times. I have a FastAPI endpoint to change the logging level without the need to restart the whole application. Every request to that endpoint calls `config_loguru()` only once.

**Comment by BabakAmini** [comment]
@Delgan I'm dynamically adding new levels to my application logger. At some point (such as when changing the logging level from the endpoint), I require access to all the level names. Currently, I can achieve this only by some non-Pythonic codes like the one below:

```Python
for x in logger.__dict__['_core'].levels:
  print(x)
```

Could you please integrate some APIs into the library that would allow us to retrieve the names and definitions of all available levels, as well as any available handlers?

**Comment by Delgan** [comment]
> I'm not calling `config_loguru()` multiple times. I have a FastAPI endpoint to change the logging level without the need to restart the whole application. Every request to that endpoint calls `config_loguru()` only once.

Although you're not explicitly calling it multiple times, the FastAPI endpoint causes `config_loguru()` to be called at least twice by the same process, right?

I'm suggesting the following workaround:

```python
initialized = False

def config_loguru(level):
    global initialized

    cfg = LoguruConfig().load('loguru.yml', configure=False)
        
    for h in cfg.handlers:
        h['level'] = level
    
    if initialized:
        # No need to add the custom levels multiple times.
        cfg.levels.clear()

    cfg.parse().configure()

    initialized = True
```


> Could you please integrate some APIs into the library that would allow us to retrieve the names and definitions of all available levels, as well as any available handlers?

Sorry, this is not planned. The handlers are not meant to be publicly exposed and manipulated. I would suggest to manually keep a list of the custom levels added.

**Comment by BabakAmini** [comment]
@Delgan Actually I call `config_loguru()` once the application is initialized and there are no issues. However, I keep encountering the mentioned error whenever the endpoint is called. So, what if I require making multiple calls to that endpoint? The application is running constantly, and I want to be able to change the logging level during its lifetime. I wonder why adding `logger.remove()` before reconfiguring the logger doesn't help. Currently, @erezinman workaround is the only way to resolve this issue.

**Comment by Delgan** [comment]
@BabakAmini Because `logger.remove()` cleanup the handlers but not the levels.

Your configuration file contains the following:

```yaml
levels:
  - name: NEW
    'no': 13
    icon: ¤
    color: ""
```

This is equivalent to calling `logger.level("NEW", no=13, icon="¤", color="")`. The `"NEW"` level can only be added once.

When your FastAPI endpoint is executed to change the logging level of handlers, it also tries to create the `"NEW"` level. If the `"NEW"` level was previously already installed, it will raise an exception.

**Comment by BabakAmini** [comment]
Thank you @Delgan, that makes sense. I thought `logger.remove()` removes all created handlers and associated levels, but the `NEW` level already exists in the dictionary:

![2024-01-23_00-40](https://github.com/erezinman/loguru-config/assets/85762931/e5f56514-93b8-43e9-a5b7-5bfb42a3c9da)

Indeed, there is no need to call `logger.remove()` as it is called automatically by `logger.configure()`. It seems that I have to call `logger.remove(NEW_level_id)` but since I have no access to the handlers id the only way is to drop the levels attribute from the config dictionary as you mentioned before.
