### ISSUE TITLE
Add loguru config to conda forge ?

### ISSUE THREAD

**Issue by znichollscr** [erezinman/loguru-config#3]
Hi @erezinman, thanks for a super nice package. I'm using it in one of my own packages (https://github.com/climate-resource/input4mips_validation) which I release on conda.

Would you be interested/willing to have loguru-config to conda-forge too? I'd be happy to do the (tiny) maintenance. I've also generated a merge request into conda forge's ecosystem if you're interested to see how this looks/works: https://github.com/conda-forge/staged-recipes/pull/27110

Up to you whether you want to be listed as a maintainer or not. I assumed that, given you created the package, you should get a chance to know where it's going!

**Comment by erezinman** [comment]
@znichollscr 
Yeah, thanks. That would be great. I'm glad that you like my package.

**Comment by znichollscr** [comment]
Ok great, please see this comment then https://github.com/conda-forge/staged-recipes/pull/27110#issuecomment-2259736900

**Comment by znichollscr** [comment]
https://anaconda.org/conda-forge/loguru-config
